export enum AuditAction {
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_SUSPEND = 'USER_SUSPEND',
  USER_REACTIVATE = 'USER_REACTIVATE',
  USER_BAN = 'USER_BAN',
  USER_UNBAN = 'USER_UNBAN',
  PERMISSION_GRANT = 'PERMISSION_GRANT',
  PERMISSION_CHANGE = 'PERMISSION_CHANGE',
}
